name: Deploy WebApp (Express) to Server Via GitHub

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to OCI via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # host: ${{ secrets.SSH_HOST }}
          host: 145.241.159.52
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          port: 22
          script: |
            set -e

            echo "Current user:"
            whoami

            echo "Current directory:"
            pwd

            echo "Repository status:"
            git status
            echo "Current branch:"
            git branch

            cd /home/${{ secrets.SSH_USERNAME }}/git-actions-test
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            docker compose up -d --build

          